'use strict';

module.exports = [
  {
    ignores: [
      'node_modules/**',
      'public/uploads/**',
      'public/dist/**',
      'coverage/**',
      'tmp/**',
      'dist-ts/**',
      'scripts/tick-*.js',
    ],
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        console: 'readonly',
        process: 'readonly',
        module: 'readonly',
        require: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        exports: 'writable',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setImmediate: 'readonly',
        clearImmediate: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        fetch: 'readonly',
        globalThis: 'readonly',
        jest: 'readonly',
        describe: 'readonly',
        test: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'none',
        },
      ],
      'no-undef': 'error',
      'no-console': 'off',
    },
  },
  {
    files: ['public/js/**/*.js'],
    languageOptions: {
      globals: {
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        FormData: 'readonly',
        FileReader: 'readonly',
        location: 'readonly',
        history: 'readonly',
        navigator: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        crypto: 'readonly',
        io: 'readonly',
        Chart: 'readonly',
        WorkHubAPI: 'readonly',
        DomSafe: 'readonly',
        WorkHubI18n: 'readonly',
        WorkHubNotifBadge: 'readonly',
        WorkHubUiBind: 'readonly',
        hostApiFetch: 'readonly',
        showToast: 'readonly',
        closeModal: 'readonly',
        openModal: 'readonly',
        navigateTo: 'readonly',
        logout: 'readonly',
        startLiveTimers: 'readonly',
        startLiveBookingTimers: 'readonly',
        globalThis: 'readonly',
      },
    },
    rules: {
      // Classic non-module scripts expose handlers for ui-bind / HTML
      'no-unused-vars': 'off',
    },
  },
  {
    files: ['test/**/*.js'],
    rules: {
      // Suite scaffolding often imports helpers not used in every file
      'no-unused-vars': 'off',
    },
  },
  {
    files: ['scripts/**/*.js'],
    rules: {
      'no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
    },
  },
];
